repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        entry: mypy
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [python, pyi]
        args: [format]
